# Generated by Django 3.0.2 on 2020-03-13 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itoneapp', '0002_journalentry_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emotion',
            old_name='emotion_icon',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='emotion',
            old_name='emotion_name',
            new_name='name',
        ),
    ]
