# Generated by Django 3.0.2 on 2020-03-16 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itoneapp', '0003_auto_20200313_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-date_journal']},
        ),
    ]
