# Generated by Django 3.0.2 on 2020-03-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itoneapp', '0005_emotion_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='color',
            field=models.CharField(max_length=40),
        ),
    ]
